package com.emsProjects.paylode;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class ProjectDto {
	private Integer projectId;
	private String blodGroup;
	private String fatherName;
    private String password;
	private String firstName;
	private String  middleName;
	private String lastName;
	private String email;
	private String officialEmail;
	private String motherName;
	private String  status;
	private String  gender;
	private String  employeeCode;
	private String mobile;
	private String officialMobile;
	private String joningDate;
	private String dateOfBirth;
	private String  marritalStatus;
	private String  uanNumber;
	private String esicNumber;
	private String  panNumber;
	private String  aadharNumber;
	private String  InsuranceNumber;
	private String drivingLicenceNumber;
	private String  ipNumber;
	private String  pfNumber;
	private String  probationPeriod;
	private String ctcAfterProbation;
	private String client;
	private String  deleverySubType;
	private String clientId;
	private String deleveryType;
	private String  presentAddressField;
	private String presentCountry;
	private String presentCity;
	private String presentState;
	private String  presentPinCode;
	private String permanentAddressField;
	private String permanentCountry;
	private String  permanentCity;
	private String permanentState;
	private String  permanentPinCode;
	private String  acHolderName_1;
	private String  ifsc_1;
	private String acNumber_1;
	private String bankName_1;
	private String  bankAddress_1;
	private String acHolderName_2;
	private String  ifsc_2;
	private String acNumber_2;
	private String  bankName_2;
	private String  bankAddress_2;
	private String  matricBoard;
	private String  matricInstitute;
	private String  matricPassingYear;
	private String  matricTotalMarks;
	private String   matricObtentMarks;
	private String  matricPercentage;
	private String  interBoard;
	private String  interInstitute;
	private String  interPassingYear;
	private String  interTotalMarks;
	private String  interObtentMarks;
	private String  interPercentage;
	private String  graduationBoard;
	private String  graduationInstitute;
	private String  graduationPassingYear;
	private String  graduationTotalMarks;
	private String  graduationObtentMarks;
	private String  graduationPercentage;
	private String  pgBoard;
	private String  pgInstitute;
	private String pgPassingYear;
	private String   pgTotalMarks;
	private String   pgObtentMarks;
	private String pgPercentage;
	private String   otherBoard;
	private String   otherInstitute;
	private String   otherPassingYear;
	private String   otherTotalMarks;
	private String   otherObtentMarks;
	private String otherPercentage;
	private String companyName;
	private String  designation;
	private String fromData;
	private String  toData;
	private String duration;
	private String employeeType;
	private String department;
	private String  selectRole;
	private String  selectSkill;
	private String   cardId;
	private String   employmentType;
	private String  subDepartment;
	private String  grade;
	private String  shift;
	private String  offerId;
	private String  desig;
	private String  site;
	private String  highestQulif;
	private String  shiftStartTime;
	private String  flexiHour;
	private String  adminRole;
	private String  allowedOD;
	private String officeAttendAlowed;
	private String  AutoAttendAlowed;
	private String  isMultiShift;
	private String  workFromHome;
	private String  geoAutoCheckIn;
	private String  rotationalweekOff;
	private String  geoAutoCheckOut;
	private String  otherLanguage;
	private String  hindiRead;
	private String  hindiWrite;
	private String hindiSpeak;
    private String  englishRead;
    private String  englishWrite;
    private String   englishSpeak;
    private String  otherLangRead;
    private String  otherLangWrite;
    private String  otherLangSpeak;
    private String relationName;
    private String  realtionType;
    private String   relationPhone;
    private String  relationDOB;
    private String  assetName;
    private String  assetModel;
    private String  assetSerial;
    private String  assetDOA;
    private String  certifiMatric;
    private String  certifiInter;
    private String  certifiGraduation;
    private String  certifiPg;
    private String  certifiother;


}
