package com.emsProjects.entity;

import jakarta.persistence.Column;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "project")
public class Project {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer projectId;
	@Column(length = 255)
	private String blodGroup;
	@Column(length = 255)
	private String fatherName;
	@Column(length = 255)
    private String password;
	@Column(length = 255)
	private String firstName;
	@Column(length = 255)
	private String  middleName;
	@Column(length = 255)
	private String lastName;
	@Column(length = 255)
	private String email;
	@Column(length = 255)
	private String officialEmail;
	@Column(length = 255)
	private String motherName;
	@Column(length = 255)
	private String  status;
	@Column(length = 255)
	private String  gender;
	@Column(length = 255)
	private String  employeeCode;
	@Column(length = 255)
	private String mobile;
	@Column(length = 255)
	private String officialMobile;
    @Column(length = 255)
	private String joningDate;
	@Column(length = 255)
	private String dateOfBirth;
	@Column(length = 255)
    private String  marritalStatus;
	@Column(length = 255)
	private String  uanNumber;
	@Column(length = 255)
	private String esicNumber;
	@Column(length = 255)
	private String  panNumber;
	@Column(length = 255)
	private String  aadharNumber;
	@Column(length = 255)
	private String  InsuranceNumber;
	@Column(length = 255)
	private String drivingLicenceNumber;
	@Column(length = 255)
	private String  ipNumber;
	@Column(length = 255)
	private String  pfNumber;
	@Column(length = 255)
	private String  probationPeriod;
	@Column(length = 255)
	private String ctcAfterProbation;
	@Column(length = 255)
	private String client;
	@Column(length = 255)
	private String  deleverySubType;
	@Column(length = 255)
	private String clientId;
	@Column(length = 255)
	private String deleveryType;
	@Column(length = 255)
	private String  presentAddressField;
	@Column(length = 255)
	private String presentCountry;
	@Column(length = 255)
	private String presentCity;
	@Column(length = 255)
	private String presentState;
	@Column(length = 255)
	private String  presentPinCode;
	@Column(length = 255)
	private String permanentAddressField;
	@Column(length = 255)
	private String permanentCountry;
	@Column(length = 255)
	private String  permanentCity;
	@Column(length = 255)
	private String permanentState;
	@Column(length = 255)
	private String  permanentPinCode;
	@Column(length = 255)
	private String  acHolderName_1;
	@Column(length = 255)
	private String  ifsc_1;
	@Column(length = 255)
	private String acNumber_1;
	@Column(length = 255)
	private String bankName_1;
	@Column(length = 255)
	private String  bankAddress_1;
	@Column(length = 255)
	private String acHolderName_2;
	@Column(length = 255)
	private String  ifsc_2;
	@Column(length = 255)
	private String acNumber_2;
	@Column(length = 255)
	private String  bankName_2;
	@Column(length = 255)
	private String  bankAddress_2;
	@Column(length = 255)
	private String  matricBoard;
	@Column(length = 255)
	private String  matricInstitute;
	@Column(length = 255)
	private String  matricPassingYear;
	@Column(length = 255)
	private String  matricTotalMarks;
	@Column(length = 255)
	private String   matricObtentMarks;
	@Column(length = 255)
	private String  matricPercentage;
	@Column(length = 255)
	private String  interBoard;
	@Column(length = 255)
	private String  interInstitute;
	@Column(length = 255)
	private String  interPassingYear;
	@Column(length = 255)
	private String  interObtentMarks;
	@Column(length = 255)
	private String  interPercentage;
	@Column(length = 255)
	private String  interTotalMarks;
	@Column(length = 255)
	private String  graduationBoard;
	@Column(length = 255)
	private String  graduationInstitute;
	@Column(length = 255)
	private String  graduationPassingYear;
	@Column(length = 255)
	private String  graduationTotalMarks;
	@Column(length = 255)
	private String  graduationObtentMarks;
	@Column(length = 255)
	private String  graduationPercentage;
	@Column(length = 255)
	private String  pgBoard;
	@Column(length = 255)
	private String  pgInstitute;
	@Column(length = 255)
	private String pgPassingYear;
	@Column(length = 255)
	private String   pgTotalMarks;
	@Column(length = 255)
	private String   pgObtentMarks;
	@Column(length = 255)
	private String pgPercentage;
	@Column(length = 255)
	private String   otherBoard;
	@Column(length = 255)
	private String   otherInstitute;
	@Column(length = 255)
	private String   otherPassingYear;
	@Column(length = 255)
	private String   otherTotalMarks;
	@Column(length = 255)
	private String   otherObtentMarks;
	@Column(length = 255)
	private String otherPercentage;
	@Column(length = 255)
	private String companyName;
	@Column(length = 255)
	private String  designation;
	@Column(length = 255)
	private String fromData;
	@Column(length = 255)
	private String  toData;
	@Column(length = 255)
	private String duration;
	@Column(length = 255)
	private String employeeType;
	@Column(length = 255)
	private String department;
	@Column(length = 255)
	private String  selectRole;
	@Column(length = 255)
	private String  selectSkill;
	@Column(length = 255)
	private String   cardId;
	@Column(length = 255)
	private String   employmentType;
	@Column(length = 255)
	private String  subDepartment;
	@Column(length = 255)
	private String  grade;
	@Column(length = 255)
	private String  shift;
	@Column(length = 255)
	private String  offerId;
	@Column(length = 255)
	private String  desig;
	@Column(length = 255)
	private String  site;
	@Column(length = 255)
	private String  highestQulif;
	@Column(length = 255)
	private String  shiftStartTime;
	@Column(length = 255)
	private String  flexiHour;
	@Column(length = 255)
	private String  adminRole;
	@Column(length = 255)
	private String  allowedOD;
	@Column(length = 255)
	private String officeAttendAlowed;
	@Column(length = 255)
	private String  AutoAttendAlowed;
	@Column(length = 255)
	private String  isMultiShift;
	@Column(length = 255)
	private String  workFromHome;
	@Column(length = 255)
	private String  geoAutoCheckIn;
	@Column(length = 255)
	private String  rotationalweekOff;
	@Column(length = 255)
	private String  geoAutoCheckOut;
	@Column(length = 255)
	private String  otherLanguage;
	@Column(length = 255)
	private String  hindiRead;
	@Column(length = 255)
	private String  hindiWrite;
	@Column(length = 255)
	private String hindiSpeak;
	@Column(length = 255)
    private String  englishRead;
	@Column(length = 255)
    private String  englishWrite;
	@Column(length = 255)
    private String   englishSpeak;
	@Column(length = 255)
    private String  otherLangRead;
	@Column(length = 255)
    private String  otherLangWrite;
	@Column(length = 255)
    private String  otherLangSpeak;
	@Column(length = 255)
    private String relationName;
	@Column(length = 255)
    private String  realtionType;
	@Column(length = 255)
    private String   relationPhone;
	@Column(length = 255)
    private String  relationDOB;
	@Column(length = 255)
    private String  assetName;
	@Column(length = 255)
    private String  assetModel;
    @Column(length = 255)
    private String  assetSerial;
    @Column(length = 255)
    private String  assetDOA;
    @Column(length = 255)
    private String  certifiMatric;
    @Column(length = 255)
    private String  certifiInter;
    @Column(length = 255)
    private String  certifiGraduation;
    @Column(length = 255)
    private String  certifiPg;
    @Column(length = 255)
    private String  certifiother;
  

	
}
